---
- hosts: Routers
  become: yes
  become_method: enable
  become_user: ansible
  tasks:
     - name: configure interfaces
       ios_l3_interface:
         name: "{{ item.name }}"
         ipv4: "{{ item.address }}"
       with_items: 
         - "{{ inter }}"
     - name: no shut to interfaces
       ios_interface:
         name: "{{ item.name }}"
         state: up
       with_items:
         - "{{ inter }}"
     - name: deploy ospf
       ios_command:
         commands:
            - configure terminal
            - router ospf 20
            - "network {{ item.ospfnetwork }} {{ item.ospfwildcast }} area {{ item.ospfarea }}"
            - do wr
       with_items: "{{ inter }}"

...
